version: '3.8'

services:
  todo_postgres:
    image: postgres:15
    container_name: todo_postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    env_file:
      - .env

  todo-api:
    build: .
    container_name: todo-api
    ports:
      - "3000:3000"
    depends_on:
      - todo_postgres
      - redis
    env_file:
      - .env
    command: ["./entrypoint.sh"]

volumes:
  pgdata:
  redis:
    driver: local
